# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pos_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("POS Application - F1D022052 - Ida Bagus Brahmanta")
        MainWindow.resize(500, 400)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        # Layout utama
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)

        # Label Produk
        self.labelProduct = QtWidgets.QLabel("Pilih Produk:", self.centralwidget)
        self.verticalLayout.addWidget(self.labelProduct)

        # Dropdown Produk
        self.productDropdown = QtWidgets.QComboBox(self.centralwidget)
        self.verticalLayout.addWidget(self.productDropdown)

        # Label Kuantitas
        self.labelQuantity = QtWidgets.QLabel("Jumlah:", self.centralwidget)
        self.verticalLayout.addWidget(self.labelQuantity)

        # Input Jumlah Barang
        self.quantityInput = QtWidgets.QSpinBox(self.centralwidget)
        self.quantityInput.setMinimum(1)
        self.verticalLayout.addWidget(self.quantityInput)

        # Label Diskon
        self.labelDiscount = QtWidgets.QLabel("Diskon:", self.centralwidget)
        self.verticalLayout.addWidget(self.labelDiscount)

        # Dropdown Diskon
        self.discountDropdown = QtWidgets.QComboBox(self.centralwidget)
        self.verticalLayout.addWidget(self.discountDropdown)

        # Tombol Tambah & Clear
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.addToCartButton = QtWidgets.QPushButton("Tambah ke Keranjang", self.centralwidget)
        self.clearButton = QtWidgets.QPushButton("Hapus", self.centralwidget)
        self.buttonLayout.addWidget(self.addToCartButton)
        self.buttonLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        # List Keranjang Belanja
        self.cartList = QtWidgets.QListWidget(self.centralwidget)
        self.verticalLayout.addWidget(self.cartList)

        # Label Total Harga
        self.totalLabel = QtWidgets.QLabel("Total: Rp. 0", self.centralwidget)
        self.verticalLayout.addWidget(self.totalLabel)

class POSApp(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Data produk
        self.products = {
            "God Of War X (Rp.100.000,00)": 100000.0,
            "GTA 8 (Rp. 200.000,00)": 200000.0,
            "Dewa Abadi (Rp.800.000,00)": 800000.0
        }

        # Isi dropdown produk & diskon
        self.productDropdown.addItem("Pilih Produk")
        self.productDropdown.addItems(self.products.keys())
        self.discountDropdown.addItems(["0%", "10%", "20%", "30%"])

        # Event Handling
        self.addToCartButton.clicked.connect(self.add_to_cart)
        self.clearButton.clicked.connect(self.clear_form)

        # Inisialisasi keranjang
        self.cart = []

    def add_to_cart(self):
        """Menambahkan item ke keranjang dengan harga setelah diskon."""
        product = self.productDropdown.currentText()
        quantity = self.quantityInput.value()
        discount = int(self.discountDropdown.currentText().replace("%", ""))

        if product == "Pilih Produk" or quantity == 0:
            self.totalLabel.setText("Invalid Input!")
            return

        price = self.products[product] * quantity
        price_after_discount = price * (1 - discount / 100)

        self.cart.append(price_after_discount)
        self.cartList.addItem(f"{product} - {quantity} x Rp.{self.products[product]:,.0f} (Disc {discount}%)")

        self.update_total()

    def clear_form(self):
        """Menghapus semua item dari keranjang dan reset form."""
        self.productDropdown.setCurrentIndex(0)
        self.quantityInput.setValue(1)
        self.discountDropdown.setCurrentIndex(0)
        self.cartList.clear()
        self.cart = []
        self.update_total()

    def update_total(self):
        """Mengupdate total harga berdasarkan isi keranjang."""
        total_price = sum(self.cart)
        self.totalLabel.setText(f"Total: Rp. {total_price:,.2f}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = POSApp()
    window.show()
    sys.exit(app.exec())
